# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 13:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CateInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='类型名')),
                ('status', models.IntegerField(choices=[(0, '删除'), (1, '正常')], default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='PostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='文章标题')),
                ('_logo', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='文章预览图')),
                ('abstract', models.CharField(max_length=300, verbose_name='文章摘要')),
                ('md_content', models.TextField(verbose_name='markdown内容')),
                ('html_content', models.TextField(verbose_name='文章内容')),
                ('status', models.IntegerField(choices=[(0, '删除'), (1, '正常')], default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='TagInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名')),
                ('status', models.IntegerField(choices=[(0, '删除'), (1, '正常')], default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('status', models.IntegerField(choices=[(0, '删除'), (1, '正常')], default=1, verbose_name='状态')),
                ('type', models.IntegerField(choices=[(0, '删除'), (1, '正常')], default=0, verbose_name='用户类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.AddField(
            model_name='postinfo',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='background.UserInfo', verbose_name='文章作者'),
        ),
        migrations.AddField(
            model_name='postinfo',
            name='cate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='background.CateInfo', verbose_name='文章类型'),
        ),
        migrations.AddField(
            model_name='postinfo',
            name='tags',
            field=models.ManyToManyField(to='background.TagInfo', verbose_name='文章标签'),
        ),
    ]
